server:
   port: 8877

logging:
    path: logs
    file: mylog.log


spring:
   application:
          name: report
   datasource:
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://127.0.0.1:3306/course?useUnicode=true&characterEncoding=utf-8&useSSL=false
       username: root
       password: liurong

mybatis:
    type-aliases-package: com.course.model
    mapper-locations:
       - mapper/*




